repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.4.1
    hooks:
      - id: prettier
        files: \.(js|jsx|ts|tsx|html|css|scss|md|yaml|yml)$

  - repo: https://github.com/psf/black
    rev: 23.3.0  # Latest version as of now
    hooks:
      - id: black
        language_version: python3.12