# Generated by Django 3.2.25 on 2024-07-27 04:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proj', '0008_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='goal_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
