name: Django CI

on:
  push:
    branches: 
      - '**'  # This will match any branch
  pull_request:
    branches: 
      - '**'  # This will match any branch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib

    - name: Configure PostgreSQL
      run: |
        sudo sed -i "s/peer/trust/g" /etc/postgresql/*/main/pg_hba.conf
        sudo sed -i "s/md5/trust/g" /etc/postgresql/*/main/pg_hba.conf
        sudo service postgresql restart

    - name: Set up the database
      run: |
        sudo -u postgres psql -c "CREATE DATABASE test_db;"

    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: your_project.settings
        DATABASE_URL: postgres://postgres@localhost/test_db
      run: |
        python manage.py migrate
        python manage.py test
