name: Django CI

on:
  push:
    branches: 
      - '**'  # This will match any branch
  pull_request:
    branches: 
      - '**'  # This will match any branch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install PostgreSQL
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql postgresql-contrib

    - name: Configure PostgreSQL
      run: |
        sudo service postgresql start
        sudo -u postgres psql -c "ALTER USER postgres PASSWORD '030105';"
        sudo sed -i "s/peer/md5/g" /etc/postgresql/*/main/pg_hba.conf
        sudo sed -i "s/ident/md5/g" /etc/postgresql/*/main/pg_hba.conf
        sudo service postgresql restart

    - name: Set up the database
      env:
        PGPASSWORD: 030105
      run: |
        sudo -u postgres psql -c "CREATE DATABASE finsages;"

    - name: Set environment variables
      run: |
        echo "DB_NAME=finsages" >> $GITHUB_ENV
        echo "DB_USER=postgres" >> $GITHUB_ENV
        echo "DB_PASSWORD=030105" >> $GITHUB_ENV
        echo "DB_HOST=127.0.0.1" >> $GITHUB_ENV
        echo "DB_PORT=5432" >> $GITHUB_ENV

    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: finsages.settings  # Replace with your actual settings module
        DB_NAME: finsages
        DB_USER: postgres
        DB_PASSWORD: 030105
        DB_HOST: 127.0.0.1
        DB_PORT: 5432
      run: |
        python manage.py migrate
        python manage.py test
