name: Django CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12  # You can use any version of PostgreSQL that matches your production setup
        env:
          POSTGRES_DB: mydb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Specify the Python version you need for your Django project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set environment variables
        run: |
          echo "DJANGO_SETTINGS_MODULE=finsage.settings" >> $GITHUB_ENV
          echo "POSTGRES_USER=user" >> $GITHUB_ENV
          echo "POSTGRES_PASSWORD=password" >> $GITHUB_ENV
          echo "POSTGRES_DB=mydb" >> $GITHUB_ENV
          echo "DB_HOST=localhost" >> $GITHUB_ENV  # localhost here refers to GitHub Actions service container

      - name: Apply migrations
        run: python manage.py migrate

      - name: Run tests
        run: python manage.py test


